$(document).ready(function(){      
     $(".slider-caption").click(function(){
        if($("#cropslide").hasClass("show")){
          $("#cropslide").removeClass("show");
          $(this).removeClass("show");
        }
        else{
          $("#cropslide").addClass("show");
          $(this).addClass("show");
          gs.show_crops();
        }
     }); 
     })